//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristicaHabitacion
    {
        public int id { get; set; }
        public int idTipoHabitacion { get; set; }
        public int idCaracteristica { get; set; }
    
        public virtual caracteristica caracteristica { get; set; }
        public virtual tipoHabitacion tipoHabitacion { get; set; }
    }
}
