//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenidoImagen
    {
        public int id { get; set; }
        public string nombreUnico { get; set; }
        public byte[] valorImagen { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idPagina { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual Pagina Pagina { get; set; }
    }
}
