//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContenidoTexto
    {
        public int id { get; set; }
        public string nombreUnico { get; set; }
        [Required]
        [MinLength(6)]
        public string valorTexto { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public string idioma { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idPagina { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual Pagina Pagina { get; set; }
    }
}
