//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilidades
    {
        public int id { get; set; }
        public byte[] Imagen { get; set; }
        public string descripcionEsp { get; set; }
        public string descripcionEn { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string ImgSrc { get; set; }
    
        public virtual hotel hotel { get; set; }
    }
}
