//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    
    public partial class obtenerDescripcionFacilidad_Result1
    {
        public int id { get; set; }
        public byte[] Imagen { get; set; }
        public string descripcionEsp { get; set; }
        public string descripcionEn { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string ImgSrc { get; set; }
    }
}
