//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteDaño
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idHabitacion { get; set; }
        public Nullable<int> idMobiliario { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual Mobiliario Mobiliario { get; set; }
    }
}
