//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idHabitacion { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public int cantidadDias { get; set; }
        public int cantidadNoches { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estado { get; set; }
        public int idTemporada { get; set; }
        public string numeroReserva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual temporada temporada { get; set; }
    }
}
