//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idHabitacion { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public int cantidadDias { get; set; }
        public int cantidadNoches { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estado { get; set; }
        public int idTemporada { get; set; }
        public string numeroReserva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual temporada temporada { get; set; }
    }
}
