//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSA2020
{
    using System;
    
    public partial class Sp_Estado_Habitaciones_Result1
    {
        public int id { get; set; }
        public Nullable<int> numero { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string Estado { get; set; }
    }
}
